import { NextResponse } from "next/server";

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { mood } = body;

    if (!mood) {
      return NextResponse.json({ error: "Mood is required" }, { status: 400 });
    }

    const apiKey = process.env.NEXT_STABILITY_API;
    if (!apiKey) {
      return NextResponse.json({ error: "Stability API key missing from environment" }, { status: 500 });
    }

    // Using Stability AI v2beta API
    const formData = new FormData();
    formData.append("prompt", `A highly artistic and creative digital artwork representing the feeling or mood: ${mood}. Masterpiece, trending on artstation, vivid colors, evocative.`);
    formData.append("output_format", "png");

    const response = await fetch(
      "https://api.stability.ai/v2beta/stable-image/generate/core",
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${apiKey}`,
          Accept: "application/json",
        },
        body: formData,
      }
    );

    if (!response.ok) {
      const errText = await response.text();
      console.error("Stability Error:", errText);
      return NextResponse.json({ error: errText || "Failed to generate image from Stability API" }, { status: response.status });
    }

    const responseJSON = await response.json();
    if (!responseJSON.image) {
      return NextResponse.json({ error: "No image generated by Stability API" }, { status: 500 });
    }

    const base64Image = responseJSON.image;
    const dataUrl = `data:image/png;base64,${base64Image}`;

    return NextResponse.json({ imageUrl: dataUrl }, { status: 200 });
  } catch (error: any) {
    console.error("Generation error:", error);
    return NextResponse.json({ error: error.message || "Internal Server Error" }, { status: 500 });
  }
}
