import { NextResponse } from "next/server";

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { moods } = body;

    if (!moods || !Array.isArray(moods) || moods.length === 0) {
      return NextResponse.json({ error: "At least one mood is required" }, { status: 400 });
    }

    const apiKey = process.env.NEXT_STABILITY_API;
    if (!apiKey) {
      return NextResponse.json({ error: "Stability API key missing from environment" }, { status: 500 });
    }

    // Advanced Prompt Synthesis Engine
    const blendString = moods.join(", ");
    const masterPrompt = `A breathtaking, abstract cinematic masterpiece visualizing the conceptual blend of the following intersecting human emotions and aesthetic concepts: [${blendString}]. Intricate lighting, highly conceptual, vivid surrealism, masterpiece heavily trending on artstation, 8k resolution, ethereal atmosphere.`;

    // Using Stability AI v2beta API
    const formData = new FormData();
    formData.append("prompt", masterPrompt);
    formData.append("output_format", "png");

    const response = await fetch(
      "https://api.stability.ai/v2beta/stable-image/generate/core",
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${apiKey}`,
          Accept: "application/json",
        },
        body: formData,
      }
    );

    if (!response.ok) {
      const errText = await response.text();
      console.error("Stability Error:", errText);
      return NextResponse.json({ error: errText || "Failed to generate image from Stability API" }, { status: response.status });
    }

    const responseJSON = await response.json();
    if (!responseJSON.image) {
      return NextResponse.json({ error: "No image generated by Stability API" }, { status: 500 });
    }

    const base64Image = responseJSON.image;
    const dataUrl = `data:image/png;base64,${base64Image}`;

    return NextResponse.json({ imageUrl: dataUrl }, { status: 200 });
  } catch (error: any) {
    console.error("Generation error:", error);
    return NextResponse.json({ error: error.message || "Internal Server Error" }, { status: 500 });
  }
}
